version: '3.4'

services:
  redisstack:
    container_name: "redis-stack"
    image: redis/redis-stack
    ports:
    - 6379:6379
    - 8001:8001
  postgressql:
    image: postgres
    container_name: postgressql
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thanh
      - POSTGRES_MULTIPLE_DATABASES=MediNet
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  medinet:
    image: ${DOCKER_REGISTRY-}medinet
    build:
      context: .
      dockerfile: MediNet/Dockerfile
    environment:
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=postgressql; Port=5432; Database=MediNet; Username=postgres; Password=thanh;
    ports:
    - "4202:80"
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
volumes:
  postgres_data: